services:
    lemon_rest.controller:
        class: Lemon\RestBundle\Controller\RestController
        arguments:
            - @lemon_rest.handler

    lemon_rest.handler:
        class: Lemon\RestBundle\Request\Handler
        arguments:
            - @lemon_rest.object_manager_factory
            - @lemon_rest.object_envelope_factory
            - @jms_serializer
            - @lemon_rest.format_negotiator
            - @logger

    lemon_rest.format_negotiator:
        class: Negotiation\FormatNegotiator

    lemon_rest.event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - @service_container

    lemon_rest.event.processor_subscriber:
        class: Lemon\RestBundle\Event\ProcessorSubscriber
        arguments:
            - @lemon_rest.object_processor
        tags:
            - { name: lemon_rest.event_subscriber }

    lemon_rest.event.validator_subscriber:
        class: Lemon\RestBundle\Event\ValidatorSubscriber
        arguments:
            - @lemon_rest.object_validator
        tags:
            - { name: lemon_rest.event_subscriber }


    lemon_rest.object_manager_factory:
        class: Lemon\RestBundle\Object\ManagerFactory
        arguments:
            - @lemon_rest.object_registry
            - @doctrine
            - @lemon_rest.event_dispatcher

    lemon_rest.object_processor:
        class: Lemon\RestBundle\Object\Processor
        arguments:
            - @doctrine
            - @jms_serializer.metadata_factory

    lemon_rest.object_validator:
        class: Lemon\RestBundle\Object\Validator
        arguments:
            - @validator

    lemon_rest.object_registry:
        class: Lemon\RestBundle\Object\Registry

    lemon_rest.object_envelope_factory:
        class: Lemon\RestBundle\Object\Envelope\EnvelopeFactory
        arguments:
            - %lemon_rest_object_envelope_class%
